pipeline {
    agent {
        docker {
            image 'python:3.10'
            args '-u root:root' // gives root permissions to install packages
        }
    }
    environment{
        DB_HOST = '192.168.12.1'
        USERNAME = 'user1'
        PASSWORD = 'password123'
        Test = 'Sent Successfully'
    }
    stages {
        stage('Install Git') {
            steps {
                sh 'apt-get update && apt-get install -y git'
                sh 'git --version'
                echo "The Database IP is ${DB_HOST}"
            }
        }
        stage('Checkout') {
            steps {
                checkout scm
                sh 'ls -ltr'
                echo "The Username is ${USERNAME}"
            }
        }
        stage('Setup') {
            steps {
                dir('01-jenkins-basics') {
                    sh 'pip install -r requirements.txt'
                    echo "The Username is ${USERNAME}"
                }
            }
        }
        stage('Test') {
            steps {
                dir('01-jenkins-basics') {
                    sh 'pytest'
                    echo "Test is ${Test}"
                }
            }
        }
    }
}
