pipeline {
    agent {
        docker {
            image 'python:3.10'
        }
    }
    stages {
        stage('Checkout') {
            steps {
                git url: 'https://github.com/momagdyy97/course-jenkins-project.git', branch: 'main'
                sh 'ls -ltr'
            }
        }
        stage('Setup') {
            steps {
                dir('01-jenkins-basics') {
                    sh 'pip install -r requirements.txt'
                }
            }
        }
        stage('Test') {
            steps {
                dir('01-jenkins-basics') {
                    sh 'pytest'
                }
            }
        }
    }
}
