pipeline {
    agent any

    environment {
        IMAGE_NAME = 'momousa1997/flask-app'
        IMAGE_TAG = "${IMAGE_NAME}:${env.BUILD_NUMBER}"
        VENV_DIR = '.venv'  // virtual environment path
    }

    stages {
        stage('Setup') {
            steps {
                dir('04-docker') {
                    sh '''
                        python3 -m venv $VENV_DIR
                        . $VENV_DIR/bin/activate
                        pip install --upgrade pip
                        pip install -r requirements.txt
                    '''
                }
            }
        }

        stage('Test') {
            steps {
                dir('04-docker') {
                    sh '''
                        . $VENV_DIR/bin/activate
                        pytest
                    '''
                }
            }
        }

        stage('Login to Docker Hub') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'docker-creds', usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD')]) {
                    sh 'echo $PASSWORD | docker login -u $USERNAME --password-stdin'
                    echo 'Login successful'
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('04-docker') {
                    sh 'docker build -t $IMAGE_TAG .'
                    echo "Docker image built successfully"
                    sh 'docker image ls'
                }
            }
        }

        stage('Push Docker Image') {
            steps {
                sh 'docker push $IMAGE_TAG'
                echo "Docker image pushed successfully"
            }
        }
    }
}
