pipeline {
    agent any

    environment {
        IMAGE_NAME = 'momousa1997/flask-app'
        IMAGE_TAG = "${IMAGE_NAME}:${env.BUILD_NUMBER}"
        PATH = "/var/lib/jenkins/.local/bin:$PATH"
    }

    stages {
        stage('Setup') {
            steps {
                dir('04-docker') {
                    sh '''
                        pip install --user --upgrade pip
                        pip install --user -r requirements.txt
                    '''
                }
            }
        }

        stage('Test') {
            steps {
                dir('04-docker') {
                    sh '''
                        ~/.local/bin/pytest
                    '''
                }
            }
        }

        stage('Login to Docker Hub') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'docker-creds', usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD')]) {
                    sh 'echo $PASSWORD | docker login -u $USERNAME --password-stdin'
                    echo 'Login successful'
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('04-docker') {
                    sh '''
                        docker build -t $IMAGE_TAG .
                        docker image ls
                    '''
                    echo "Docker image built successfully"
                }
            }
        }

        stage('Push Docker Image') {
            steps {
                sh '''
                    docker push $IMAGE_TAG
                '''
                echo "Docker image pushed successfully"
            }
        }
    }
}
